version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: "nginx-${PROJECT_NAME}"
    restart: always
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_PORT_SSL}:443"
    volumes:
      - ./app:/var/www/app:rw
      - ./.docker/nginx/conf.d/nginx.template:/etc/nginx/conf.d/nginx.template:rw
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    env_file:
      - .env

  php-fpm:
    build: ./.docker/php-fpm
    container_name: "app-${PROJECT_NAME}"
    volumes:
      - ./app:/var/www/app:rw
      - ./.docker/php-fpm/conf/php.ini:/usr/local/etc/php/php.ini:rw
      - ./.docker/php-fpm/supervisord.conf:/etc/supervisor/supervisord.conf
    depends_on:
      - nginx
      - mysql
    ports:
      - 80
      - 433
    env_file:
      - .env

  mysql:
    image: mysql:8
    container_name: "mysql-${PROJECT_NAME}"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
